<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Trapezoid.ico</ApplicationIcon>
    <AssemblyName>Trapezoid</AssemblyName>
    <RootNamespace>Trapezoid</RootNamespace>
    <Version>1.2.0</Version>
  </PropertyGroup>
</Project>
